# Generated by Django 4.0.6 on 2022-09-18 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minting', '0003_simpleuser_remove_artist_art_art_art_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='time_creation',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 18, 12, 58, 27, 638360, tzinfo=utc)),
        ),
    ]
