# Generated by Django 4.0.6 on 2022-09-09 09:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minting.art'),
        ),
        migrations.AddField(
            model_name='artist',
            name='mail',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('\\w*?\\.\\w*?\\w{5,10}\\.com')]),
        ),
    ]
