# Generated by Django 4.0.6 on 2022-09-18 12:57

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('minting', '0002_artist_art_artist_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='art',
        ),
        migrations.AddField(
            model_name='art',
            name='art_owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='art',
            name='time_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 57, 51, 604912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_cid',
            field=models.CharField(max_length=43, null=True, unique=True, validators=[django.core.validators.RegexValidator('^Qm\\w{44}')]),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_description',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_name',
            field=models.CharField(max_length=27, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_tokenId',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='art_tokenURI',
            field=models.URLField(max_length=256, null=True, unique=True),
        ),
    ]
